name: stream_ext
version: 0.0.1
author: Yan Cui <theburningmonk@gmail.com>
description: Extension functions for Stream class
homepage: https://github.com/theburningmonk/stream_ext
dependencies:
  browser: any
  js: any
  unittest: any
